version: "3.9"
# SearXNG — Dedicated Private Search Service
services:
  valkey:
    image: docker.io/valkey/valkey:9-alpine3.24
    container_name: valkey
    restart: always
    volumes:
      - ./data-valkey:/data
    healthcheck:
      test: ["CMD","valkey-cli -p 6379 ping | grep PONG"]
      interval: 5s
      timeout: 1s
      retries: 5
      start_period: 3s
    networks:
      - searxng-net
  searxng:
    image: docker.io/searxng/searxng:2026.7.24-4f64d9501
    container_name: searxng
    restart: always
    depends_on:
      valkey:
        condition: service_healthy
    volumes:
      - ./config/searxng-settings.yml:/etc/searxng/settings.yml:ro,Z
      - ./config/limiter.toml:/etc/searxng/limiter.toml:ro,Z
      - ./config/ip_limit.py:/usr/local/searxng/searx/botdetection/ip_limit.py:ro,Z
      - ./data-searxng:/var/lib/searxng
    environment:
      # Secret key for the server
      - SEARXNG_SECRET_KEY=${SEARXNG_SECRET_KEY:-changeit}
      # Time (sec) before sliding window for burst requests expires
      - SEARXNG_BURST_WINDOW=20
      # Maximum requests from one IP in the BURST_WINDOW
      - SEARXNG_BURST_MAX=20
      # Maximum of suspicious requests from one IP in the BURST_WINDOW
      - SEARXNG_BURST_MAX_SUSPICIOUS=5
      # Time (sec) before the longer sliding window expires
      - SEARXNG_LONG_WINDOW=60
      # Maximum requests from one IP in the LONG_WINDOW
      - SEARXNG_LONG_MAX=30
      # Maximum suspicious requests from one IP in the LONG_WINDOW
      - SEARXNG_LONG_MAX_SUSPICIOUS=15
      # Time (sec) before sliding window for one suspicious IP expires
      - SEARXNG_SUSPICIOUS_IP_WINDOW=60
      # Maximum requests from one suspicious IP in the SUSPICIOUS_IP_WINDOW
      - SEARXNG_SUSPICIOUS_IP_MAX=3
      # Enable link token for bot detection
      - SEARXNG_LINK_TOKEN=true
      # Filter link-local networks
      - SEARXNG_FILTER_LINK_LOCAL=false
    networks:
      - searxng-net

  nginx:
    image: docker.io/nginx:stable-alpine3.24-perl 
    container_name: nginx
    restart: always
    ports:
      - 8888:80
      - 443:443
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx-logs:/var/log/nginx
    depends_on:
      searxng:
        condition: service_started
    networks:
      - searxng-net

networks:
  searxng-net:
    driver: bridge

